#!/usr/bin/env python3
"""Debug: Trigger PTZ move + capture events"""
import json, time
from onvif import ONVIFCamera
from zeep.helpers import serialize_object

cam = ONVIFCamera("192.168.178.25", 80, "Moloch_4.5", "Auge666")
media = cam.create_media_service()
ptz = cam.create_ptz_service()
profiles = media.GetProfiles()
token = profiles[0].token

# Create subscription BEFORE the move
pullpoint = cam.create_pullpoint_service()
print("Subscription created. Pulling initial events...")

# Drain initial events
try:
    init = pullpoint.PullMessages({'Timeout': 'PT2S', 'MessageLimit': 50})
    n = init.NotificationMessage
    print(f"Initial drain: {len(n) if n else 0} events")
    if n:
        for i, ev in enumerate(n):
            topic = getattr(ev, 'Topic', None)
            v1 = getattr(topic, '_value_1', '') if topic else ''
            print(f"  Init event {i+1}: {v1}")
except Exception as e:
    print(f"Drain error (ok): {e}")

# Get current position
status = ptz.GetStatus({'ProfileToken': token})
pos = status.Position
pt = getattr(pos, 'PanTilt', None)
print(f"\nCurrent position: pan={getattr(pt,'x',0)} tilt={getattr(pt,'y',0)}")

# Small relative move
print("\nTriggering small relative PTZ move (pan +10)...")
try:
    ptz.RelativeMove({
        'ProfileToken': token,
        'Translation': {
            'PanTilt': {'x': 10.0, 'y': 0.0},
            'Zoom': {'x': 0.0}
        }
    })
    print("Move command sent!")
except Exception as e:
    print(f"RelativeMove error: {e}")
    # Try continuous move instead
    print("Trying ContinuousMove...")
    try:
        ptz.ContinuousMove({
            'ProfileToken': token,
            'Velocity': {
                'PanTilt': {'x': 0.5, 'y': 0.0},
                'Zoom': {'x': 0.0}
            }
        })
        time.sleep(1)
        ptz.Stop({'ProfileToken': token, 'PanTilt': True, 'Zoom': True})
        print("ContinuousMove + Stop done!")
    except Exception as e2:
        print(f"ContinuousMove error: {e2}")

# Wait for events
time.sleep(3)

# Check new position
status2 = ptz.GetStatus({'ProfileToken': token})
pos2 = status2.Position
pt2 = getattr(pos2, 'PanTilt', None)
print(f"\nNew position: pan={getattr(pt2,'x',0)} tilt={getattr(pt2,'y',0)}")

# Pull events after move
print("\nPulling events after move...")
try:
    msgs = pullpoint.PullMessages({'Timeout': 'PT5S', 'MessageLimit': 50})
    notifs = msgs.NotificationMessage
    print(f"Events after move: {len(notifs) if notifs else 0}")
    if notifs:
        for i, ev in enumerate(notifs):
            topic = getattr(ev, 'Topic', None)
            topic_str = str(getattr(topic, '_value_1', '')) if topic else ''

            msg = getattr(ev, 'Message', None)
            inner = getattr(msg, 'Message', msg) if msg else None

            src_items = []
            data_items = []
            if inner:
                source = getattr(inner, 'Source', None)
                if source:
                    for item in (getattr(source, 'SimpleItem', []) or []):
                        src_items.append(f"{item.Name}={item.Value}")
                data = getattr(inner, 'Data', None)
                if data:
                    for item in (getattr(data, 'SimpleItem', []) or []):
                        data_items.append(f"{item.Name}={item.Value}")

            print(f"  [{i+1}] Topic: {topic_str}")
            print(f"       Source: {', '.join(src_items) if src_items else '-'}")
            print(f"       Data: {', '.join(data_items) if data_items else '-'}")

            # Full dump
            try:
                ser = serialize_object(ev)
                print(f"       Full: {json.dumps(ser, indent=6, default=str)[:500]}")
            except:
                pass
            print()
    else:
        print("  No events generated by PTZ move")
except Exception as e:
    print(f"Pull error: {e}")

# Move back to center
print("\nMoving back to 0,0...")
try:
    ptz.AbsoluteMove({
        'ProfileToken': token,
        'Position': {
            'PanTilt': {'x': 0.0, 'y': 0.0},
            'Zoom': {'x': 0.0}
        }
    })
    print("AbsoluteMove to center sent!")
except Exception as e:
    print(f"AbsoluteMove error: {e}")

time.sleep(2)
status3 = ptz.GetStatus({'ProfileToken': token})
pos3 = status3.Position
pt3 = getattr(pos3, 'PanTilt', None)
print(f"Final position: pan={getattr(pt3,'x',0)} tilt={getattr(pt3,'y',0)}")
